### ISSUE TITLE
[FeatureRequest] Support for Tagging DSD Files (e.g., .dsf, .dff)

### ISSUE THREAD

**Issue by chenghuangqobuz** [Zereges/id3-tag-cli#1]
Hello,

First of all, thank you for creating and maintaining id3-tag-cli. It’s a great tool for managing metadata across various audio formats.

**Feature Request:**
I would like to request the addition of support for tagging DSD (Direct Stream Digital) files, specifically .dsf and .dff formats.

**Use Case:**
DSD files are commonly used in high-resolution audio environments and are increasingly popular among audiophiles. Being able to tag these files with id3-tag-cli would significantly enhance the tool’s versatility, allowing users to manage their entire music library, including high-resolution audio, from a single command-line interface.

**Comment by Zereges** [comment]
Hi, thank you for the feature request. I'll check out those formats and see if I can add support.

**Comment by Zereges** [comment]
This project uses [TagLib](https://taglib.org/) as backend and it already supports DSD files (even at the version this project ships with).

Have you tried it?

**Comment by chenghuangqobuz** [comment]
I attempted to process the file, but I encountered the following error: "Couldn't process given file /Users/**/Desktop/Wake Up Dead.dsf."

**Comment by chenghuangqobuz** [comment]
I have one question (I'm not so familiar with Linux/macOS): For Linux and macOS, how can I generate the command line version of the application? Thanks

**Comment by chenghuangqobuz** [comment]
Hi,

Thank you for the updated code.

I followed your documentation to generate a Mac version and created a Makefile. I installed TagLib version 1.31.1 via Homebrew.

However, it seems the issue might be related to the installation at /opt/homebrew/opt/taglib/include/taglib, as I couldn’t find any references to DSD support in the source files. This could be why it’s not working as expected.

<img width="1200" alt="Screenshot 2024-08-24 at 09 11 53" src="https://github.com/user-attachments/assets/4164ceba-3eb0-4928-8155-70f16332e0c3">


I’ll try compiling TagLib on my Mac and will test again.

Really appreciate your support — thanks again!

**Comment by Zereges** [comment]
Sorry, I was away from internet. I will check this during this week. Can you check the [TagLib](https://github.com/taglib/taglib) directly? Their documentation says

> Currently, it supports both ID3v1 and ID3v2 for MP3 files, [Ogg Vorbis](https://xiph.org/vorbis/) comments and ID3 tags in [FLAC](https://xiph.org/flac/), MPC, Speex, WavPack, TrueAudio, WAV, AIFF, MP4, APE, ASF, DSF, DFF and AAC files.

Also, can you share the input file? If not, I could add some extra debugging and would ask for an output.

**Comment by Zereges** [comment]
It seems that the TagLib added support only in 2.0.

> Support for Direct Stream Digital (DSD) stream files (DSF) and interchange
file format (DSDIFF, DFF), ADTS (AAC) files.

The current version of id3-tag-cli works with 2.0, but it's not yet in all package repositories (i.e. Debian is still with 1.13, Homebrew also seems to use only 1.13).

Compiling TagLib 2.0 on Linux and linking id3-tag-cli against it works with DSD files.

**Comment by chenghuangqobuz** [comment]
Hi again, 

Thanks for the sharing. 

I noticed that version 1.0 seems to have much better support for certain functionalities compared to version 1.10. Is there a particular reason why those features were removed or altered in the newer release? It would be helpful to understand the rationale behind these changes, as they seem to affect compatibility with some use cases.

**It might have been added by a previous colleague of mine, but I haven’t been able to track down the source code for it.**


```
 ./id3-tag-cli --version
id3-tags-cli 
License GPL-3.0: GNU GPL version 3 <https://www.gnu.org/licenses/>
This is free software: you are free to change and redistribute it.
This program comes with ABSOLUTELY NO WARRANTY!

Written by Zereges <https://github.com/Zereges/id3-tag-cli>
1.0


 ./id3-tag-cli --help
id3-tag-cli
Usage: ./id3-tag-cli [OPTIONS] [file]

Positionals:
  file TEXT:FILE              File to process

Options:
  -h,--help                   Print this help message and exit
  --config                    Read an ini file
  --print                     Print configuration and exit
  --version                   Display program version information and exit


Tags:
  -a,--artist TEXT            Sets the Artist/Performer.
  -t,--title TEXT             Sets the Title/Song name/Content.
  -A,--album TEXT             Sets the Album/Movie/Show title.
  -y,--year INT               Sets the Year.
  -T,--track INT              Sets the Track number/Position.
  -g,--genre TEXT             Sets the Genre.
  -c,--comment TEXT           Sets the Description/Comment.
  --albumArtist,--performer TEXT
  --composer TEXT             
  --copyright TEXT            
  --discnumber INT            
  --disctotal INT             
  --encodedby TEXT            
  --isrc TEXT                 
  --license,--owner TEXT      
  -p,--picture TEXT           Sets Picture contained in file.
  --trackId TEXT              
  --tracknumber INT           
  --tracktotal INT            
  --work,--subtitle TEXT   
```


```
Usage: ./id3-tag-cli-new [options] file

    -h |     --help    Prints this help and exits.
    -v |  --version    Prints version information and exits.
    -a |   --artist    [STR] Sets the Artist/Performer.
    -t |    --title    [STR] Sets the Title/Song name/Content.
    -A |    --album    [STR] Sets the Album/Movie/Show title.
    -y |     --year    [INT] Sets the Year.
    -T |    --track    [INT] Sets the Track number/Position.
    -g |    --genre    [STR] Sets the Genre.

  [STR] -  String type
  [INT] - Integer type

  If no arguments are specified, information of given file is retrieved.
  If the option is not specified, the value is unchanged.
  If the argument is empty string ("") (for [STR]) or 0 (for [INT]) the value is cleared.
```

**Comment by Zereges** [comment]
The help message you linked was never present in the source code. If you made any amends to code I haven't seen them. This tool only worked with the following properties

```
    -a |   --artist    [STR] Sets the Artist/Performer.
    -t |    --title    [STR] Sets the Title/Song name/Content.
    -A |    --album    [STR] Sets the Album/Movie/Show title.
    -y |     --year    [INT] Sets the Year.
    -T |    --track    [INT] Sets the Track number/Position.
    -g |    --genre    [STR] Sets the Genre.
```

**Comment by chenghuangqobuz** [comment]
Hi again, Yes, we didn't modify any customer code, but when I run the executable you provided, I encountered this error:

<img width="305" alt="Screenshot 2024-10-14 at 12 02 57" src="https://github.com/user-attachments/assets/f4f31c44-4a3e-4be5-b749-33b027eaa43f">


Do you have any idea what might be causing this? I really appreciate your help.

**Comment by kliberf** [comment]
Try intsalling the latest [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) (this [link](https://aka.ms/vs/17/release/vc_redist.x64.exe) should be most relevant)

**Comment by Zereges** [comment]
Try intsalling the latest [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) (this [download](https://aka.ms/vs/17/release/vc_redist.x64.exe) should be most relevant).
